### ISSUE TITLE
Cannot find m.lib

### ISSUE THREAD

**Issue by yafeya** [derselbst/ARSS#1]
Hi,

I am using this ARSS on windows, and when I would like to compile it on windows, there is always need a m.lib, where can I find this m.lib? Thanks.
Steps to compile:
1. create a build folder in the source,
2. execute "cmake .."
3. open the vcproject generated by cmake, then set fftw as C++/link folder.
4. then build, it said that i missed a "m,lib".

Where can i find this m.lib? Thanks

**Comment by derselbst** [comment]
m.lib is only relevant for Linux, on Windows you don't need it. Edit the file below, remove the m and try again. If it works, pls. let me know so that I can commit a proper fix.

https://github.com/derselbst/ARSS/blob/1f02424991356fc7b65bb803cedc31cd972598ef/src/CMakeLists.txt#L38

**Comment by yafeya** [comment]
Yes, it's working, thanks.
